apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-exchange-rate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-exchange-rate
  template:
    metadata:
      labels:
        app: spring-boot-exchange-rate
    spec:
      serviceAccountName: admin-role-sa
      containers:
        - name: spring-boot-exchange-rate
          image: rolandojavier13/spring-boot-exchange-rate:v1.0.8
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources:
            requests:
              memory: "512Mi"
              cpu: "256m"
            limits:
              memory: "1024Mi"
              cpu: "512m"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-exchange-rate
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: spring-boot-exchange-rate
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-exchange-rate
  annotations:
#    nginx.ingress.kubernetes.io/use-regex: "true"
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /trade-banking/currency/v1
            pathType: Prefix
            backend:
              service:
                name: spring-boot-exchange-rate
                port:
                  number: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-exchange-rate-dev
data:
#  application.yaml: |-
#    api:
#      configuration:
#        description: this is a default description
#  spring-boot-exchange-rate.yaml: |-
#    api:
#      configuration:
#        description: this is a no profile description
  spring-boot-exchange-rate-dev.yaml: |-
    api:
      configuration:
        description: this is a dev description
#  spring-boot-exchange-rate-cert.yaml: |-
#    api:
#      configuration:
#        description: this is a cert description
#  spring-boot-exchange-rate-prod.yaml: |-
#    api:
#      configuration:
#        description: this is a prod description

---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: spring-boot-exchange-rate
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: spring-boot-exchange-rate
#  minReplicas: 1
#  maxReplicas: 2
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 120
#    - type: Resource
#      resource:
#        name: memory
#        target:
#          type: Utilization
#          averageUtilization: 120
#