server:
  port: ${PORT:8081}

spring:
  application:
    name: business-exchange-rate
  datasource:
    url: jdbc:h2:mem:testdb
    h2:
      console:
        enabled: true
        path: /h2
  webflux:
    base-path: /trade-banking/currency/v1


